name: 'Wait a minute...'
author: 'Charles Lechasseur'
description: 'Dismisses PR reviews when the PR diff changes'
inputs:
  github-token:
    description: Value of the GITHUB_TOKEN secret
    required: true
  dismiss-message:
    description: Message used when dismissing PR reviews
    required: false
    default: 'Dismissed by waitaminute because PR diff changed.'
outputs:
  diff-changed:
    description: Set to 'true' if the PR diff changed
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'alert-circle'
  color: 'blue'
