name: 'Wait a minute...'
author: 'Charles Lechasseur'
description: 'Dismisses PR reviews when the PR diff changes'
inputs:
  github-token:
    description: Value of the GITHUB_TOKEN secret
    required: true
  dismiss-message:
    description: Message used when dismissing PR reviews
    required: false
    default: 'Dismissed by waitaminute because PR diff changed.'
  target-branch:
    description: If set, action will only consider PRs targeting this base branch
    required: false
  target-branch-filter:
    description: Like target-branch, but interpreted as a regex; if both this and target-branch are set, base branch must match both filters
    required: false
  target-branch-filter-flags:
    description: If target-branch-filter is set, this can be used to pass regex flags. By default, will create a case-insensitive regex.
    required: false
    default: 'i'
outputs:
  diff-changed:
    description: Set to 'true' if the PR diff changed
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'alert-circle'
  color: 'blue'
