const WAITAMINUTE_ARTIFACT_NAME = 'waitaminute-data';
const CURRENT_DIFF_DIR_NAME = 'current-diff';

exports.WAITAMINUTE_ARTIFACT_NAME = WAITAMINUTE_ARTIFACT_NAME;
exports.CURRENT_DIFF_DIR_NAME = CURRENT_DIFF_DIR_NAME;
